services:
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db
  api:
    build: ./api
    ports:
      - "80:80"
    volumes:
        - ./api/src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root